#!/bin/sh -e
#
# Decodes a cookie created by mod_uid or ngx_http_userid_module.

if [ "$#" -ne 1 ]; then
	echo "Usage: $(basename "$0") COOKIE"
	exit 0
fi

echo "$1" | base64 -d | od -A n -t x4 | tr -d " " | tr '[:lower:]' '[:upper:]'
