#!/bin/sh

if [ "$#" -lt 1 ]; then
    echo "Usage: $(basename "$0") URL"

    exit 1
fi

youtube-dl --dump-json "${1}" | \
    jq -r '[ .formats[] | select(.protocol == "m3u8_native") | .manifest_url ][-1]'
