[tool.poetry]
name = "bookmarkmgr"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
aiohttp = "^3.8.5"
aiohttp-retry = {git = "https://github.com/inyutin/aiohttp_retry.git"}
curl-cffi = "^0.5.9"
enlighten = "^1.12.0"
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
