name: CI
on: push
permissions: {}
jobs:
  lint-all:
    name: Lint (all)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: super-linter/super-linter/slim@v7.3.0
        env:
          FILTER_REGEX_EXCLUDE: ^(bookmarkmgr|bookmarks4diff|ytm)/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYINK: false
          VALIDATE_PYTHON_PYLINT: false
  lint-subproject:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    strategy:
      matrix:
        subproject:
          - bookmarkmgr
          - bookmarks4diff
          - ytm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Don't build native modules
        if: matrix.subproject == 'bookmarkmgr'
        run: echo > build.py
      - uses: super-linter/super-linter/slim@v7.3.0
        env:
          DEFAULT_WORKSPACE: /github/workspace/${{ matrix.subproject }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          PYTHON_MYPY_CONFIG_FILE: pyproject.toml
          PYTHON_RUFF_CONFIG_FILE: pyproject.toml
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_PYINK: false
          VALIDATE_PYTHON_PYLINT: false
